site_name: Agvise AI Seminar Handouts

nav:
  - 'Welcome': 'index.md' # This points to docs/index.md
  - '1. Agenda & Overview':
    - 'Seminar Agenda': '1. Agenda & Overview/Seminar_Agenda.md' # Or rename Seminar_Agenda.md to index.md in that folder and link to '1. Agenda & Overview/index.md'
  - '2. Prompting Guides & Examples':
    - 'Advanced AI Prompting Tips': '2. Prompting Guides & Examples/Advanced_AI_Prompting_Tips.md'
    - 'CRAFT Prompting Framework': '2. Prompting Guides & Examples/CRAFT_Prompting_Framework.md'
    - 'Prompt Chaining Techniques': '2. Prompting Guides & Examples/Prompt_Chaining_Techniques.md'
    - 'Prompt Examples Value Adding': '2. Prompting Guides & Examples/Prompt_Examples_Value_Adding.md'
    - 'Prompt Playbook for Consultants': '2. Prompting Guides & Examples/Prompt_Playbook_for_Consultants.md'
  - '3. Foundational Concepts & Discussion Points':
    - 'AI Core Tensions Handout': '3. Foundational Concepts & Discussion Points/AI_Core_Tensions_Handout.md'
    - 'AI Unlocking Impossible Tasks': '3. Foundational Concepts & Discussion Points/AI_Unlocking_Impossible_Tasks.md'
    - 'Secure & Sustainable AI Use': '3. Foundational Concepts & Discussion Points/Secure_Sustainable_AI_Use.md'
  - '4. Worksheets & Data':
    - 'Mock Crop Data': '4. Worksheets & Data/agvise_mock_crop_data.csv'
    - 'Personal AI Challenge Worksheet': '4. Worksheets & Data/Personal_AI_Challenge_Worksheet.md'
  - '5. Wrap-Up':
    - 'Seminar Wrap and Key Takeaways': '5. Wrap-Up/Seminar_Wrap_and_Key_Takeways.md'
  - '6. Post-Seminar Materials':
    - 'Evaluation & Followup Options': '6. Post-Seminar Materials/Agvise_Evaluation_Followup_Options.md'

theme:
  name: material # Or any other theme you prefersite_name

