# .github/workflows/deploy.yml

name: Deploy MkDocs to GitHub Pages

on:
  push:
    branches:
      - main # Trigger the workflow on pushes to the main branch
  workflow_dispatch: # Allows manual triggering of the workflow from GitHub Actions tab

# Add this permissions block
permissions:
  contents: write # This grants write access to the repository contents
  pages: write    # This is specifically for GitHub Pages deployments
  id-token: write # Required for OpenID Connect (OIDC) authentication, good practice

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install MkDocs and dependencies
        run: |
          pip install mkdocs mkdocs-material

      - name: Deploy MkDocs site
        run: mkdocs gh-deploy --force

